
on:
  push:
    branches:
      - main
  # every hour    
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

name: Sync GitHub to Jira

jobs:
  sync:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Restore state from previous run using GitHub variables (no secret inside)
        run: |
          if [ -z "${{ vars.SYNC_STATE }}" ]; then
            echo "no previous persisted state"
          else
            echo "restoring previous sync state"
            echo "${{ vars.SYNC_STATE }}" > sync-state.yaml
            cat sync-state.yaml
          fi

      - name: Run GitHub to Jira Action
        uses: benoitf/github-to-jira-action@next
        with:
          jira-host: ${{ secrets.JIRA_HOST }}
          jira-write-token: ${{ secrets.JIRA_WRITE_TOKEN }}
          github-read-token: ${{ secrets.READ_GITHUB_TOKEN }}

        # save the state using a custom token as default GITHUB_TOKEN does not have the required permissions
        # to save variables
      - name: persist state
        env:
          GH_TOKEN: ${{ secrets.SET_VARIABLE_GITHUB_TOKEN }}
        run: |
          # use gh cli to save the content of a file into a variable
          gh variable set SYNC_STATE < sync-state.yaml
